blank_issues_enabled: false
contact_links:
  - name: Get help
    url: https://github.com/sapegin/mrm/discussions/new?category=q-a
    about: If you canâ€™t get something to work the way you expect, open a question in our discussion forums.
  - name: Report a bug
    url: https://github.com/sapegin/mrm/discussions/new?category=bugs
    about: If something is broken in the project itself, create a bug report.
