name: Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Set up Git
        run: |
          git config --global user.name "Mrm Bot"
          git config --global user.email "${BOT_EMAIL}"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/sapegin/mrm.git"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Set up npm
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> ~/.npmrc 2> /dev/null
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - name: Publish
        run: |
          npx lerna version --yes --create-release=github
          npx lerna publish from-git --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
